--- #YAML:1.0
name:               Net-Frame-Tools
version:            1.03
abstract:           useful network utilities created using Net::Frame
author:
    - GomoR <gomor-cpan_at_gomor.org>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::Frame:          0
    Net::Frame::Device:  0
    Net::Frame::Dump:    0
    Net::Frame::Simple:  0
    Net::Netmask:        0
    Net::Write:          1.00
    Term::ReadLine:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
