--- #YAML:1.0
name:                Net-Frame-Tools
version:             1.02
abstract:            useful network utilities created using Net::Frame
license:             artistic
author:              
    - GomoR <perl@gomor.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::Frame:                    0
    Net::Frame::Device:            0
    Net::Frame::Dump:              0
    Net::Frame::Simple:            0
    Net::Netmask:                  0
    Net::Write:                    1.00
    Term::ReadLine:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
